# Generated by Django 3.2.8 on 2021-10-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(db_index=True, max_length=255)),
                ('installation_name', models.CharField(db_index=True, max_length=255)),
                ('license', models.IntegerField(help_text='Installation license number')),
                ('stretchers', models.IntegerField(blank=True, db_index=True, help_text='Available Stretchers', null=True)),
                ('patients', models.IntegerField(blank=True, db_index=True, help_text='Patients on stretchers', null=True)),
                ('patients_24', models.IntegerField(blank=True, help_text='Patients on stretchers for more than 24h', null=True)),
                ('patients_48', models.IntegerField(blank=True, help_text='Patients on stretchers for more than 48h', null=True)),
                ('extracted_at', models.TimeField()),
                ('updated_at', models.DateTimeField()),
                ('model_created_at', models.DateTimeField(auto_now_add=True)),
                ('model_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
